"""Bug dans la colonne statut

Revision ID: 2f82281a9d83
Revises: 07fb827c679a
Create Date: 2021-08-09 22:13:56.931851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f82281a9d83'
down_revision = '07fb827c679a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signalement', sa.Column('statut', sa.Enum('new', 'opened', 'closed', name='signalementstatut'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signalement', 'statut')
    # ### end Alembic commands ###
