"""Initial migration

Revision ID: 8e235394d9a1
Revises: 
Create Date: 2021-07-16 16:40:43.154302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e235394d9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signalement', sa.Column('numero_suivi', sa.String(length=36), nullable=True))
    op.alter_column('signalement', 'temoin',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.create_unique_constraint(None, 'signalement', ['numero_suivi'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signalement', type_='unique')
    op.alter_column('signalement', 'temoin',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('signalement', 'numero_suivi')
    # ### end Alembic commands ###
