"""signalement date

Revision ID: a03f812c2212
Revises: 8e235394d9a1
Create Date: 2021-07-29 13:27:50.777762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03f812c2212'
down_revision = '8e235394d9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signalement', sa.Column('date_signalement', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signalement', 'date_signalement')
    # ### end Alembic commands ###
