"""signalement statut

Revision ID: b5195ec206f5
Revises: a03f812c2212
Create Date: 2021-07-29 13:34:49.252339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5195ec206f5'
down_revision = 'a03f812c2212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signalement', sa.Column('statut', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signalement', 'statut')
    # ### end Alembic commands ###
